modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/DevDyna/DataThings/issues"
license="MIT"
[[mods]]
    modId="numismatic_reforged_bounties"
    version="1.0"
    displayName="Numismatic Reforged Bounties"
    description="Bountiful addon that change many trades to use Numismatic Overhaul Reforged coins (support other forks)"
	authors="DevDyna"
	logoFile="pack.png"

[[dependencies.numismatic_reforged_bounties]]
    modId="bountiful"
    mandatory= true
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.numismatic_reforged_bounties]]
    modId="extrabounties"
    mandatory= false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"