//system
export const Reset = "\x1b[0m"
export const Bright = "\x1b[1m"
export const Dim = "\x1b[2m"
export const Underscore = "\x1b[4m"
export const Blink = "\x1b[5m"
export const Reverse = "\x1b[7m"
export const Hidden = "\x1b[8m"
//default (dark)
export const Black = "\x1b[30m"
export const Red = "\x1b[31m"
export const Green = "\x1b[32m"
export const Yellow = "\x1b[33m"
export const Blue = "\x1b[34m"
export const Magenta = "\x1b[35m"
export const Cyan = "\x1b[36m"
export const White = "\x1b[37m"
export const Gray = "\x1b[90m"
//light colors
export const LBlack = "\x1b[1m\x1b[30m"
export const LRed = "\x1b[1m\x1b[31m"
export const LGreen = "\x1b[1m\x1b[32m"
export const LYellow = "\x1b[1m\x1b[33m"
export const LBlue = "\x1b[1m\x1b[34m"
export const LMagenta = "\x1b[1m\x1b[35m"
export const LCyan = "\x1b[1m\x1b[36m"
export const LWhite = "\x1b[1m\x1b[37m"
export const LGray = "\x1b[1m\x1b[90m"
//big color
export const BBlack = "\x1b[40m"
export const BRed = "\x1b[41m"
export const BGreen = "\x1b[42m"
export const BYellow = "\x1b[43m"
export const BBlue = "\x1b[44m"
export const BMagenta = "\x1b[45m"
export const BCyan = "\x1b[46m"
export const BWhite = "\x1b[47m"
export const BGray = "\x1b[100m"