name: 🚀 New Feature
description: All good ideas can be usefull !
labels: [enhancement, need support]
assignees: DevDyna
body:
  - type: checkboxes
    id: new-issue
    attributes:
      label: Core Section
      description: Biip Boop , Something happen !
      options:
        - label: I have searched for this issue on this repository
          required: true

  - type: input
    id: text-box
    attributes:
      label: Mods related
      placeholder: extrabounties
      description: What mod did you intend ? (allow multiple mods)
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Description
      description: A clean description with images when possible
      placeholder: ln x- ln y
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: Links related to possible new mods or anything else that could be useful to know
      placeholder: (ln x- ln y)^-1
    validations:
      required: false
