name: 🐞 Numismatic-Bounties Bug Report
description: Have you found a bug ? Squash it!
labels: [bug, need support, numismatic-bounties]
assignees: DevDyna
body:
  - type: checkboxes
    id: new-issue
    attributes:
      label: Core Section
      description: Biip Boop , Something happen !
      options:
        - label: I have searched on opened issues of this repository
          required: true

          
          
  - type: textarea
    id: other
    attributes:
      label: Description
      description: description with image
      placeholder: ln x- ln y
    validations:
      required: true
