modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/DevDyna/DataThings/issues/new?template=extra-bounties-bug.yaml"
license="MIT"
[[mods]]
    modId="extrabounties"
    version="1.2"
    displayName="ExtraBounties"
    description="Bountiful addon to make it compatible with other mods"
	authors="DevDyna"
	logoFile="pack.png"