modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL=""
license="MIT"
[[mods]]
    modId="extrabounties"
    version="1.0"
    displayName="ExtraBounties"
    description="Bountiful addon to make it compatible with other mods"
	authors="DevDyna"
	logoFile="pack.png"