modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/DevDyna/DataThings/issues"
license="MIT"
[[mods]]
    modId="lightmans_currency_bounties"
    version="1.0"
    displayName="Lightmans Currency Bounties"
    description="Bountiful addon that change many trades to use Lightmans Currency coins"
	authors="DevDyna"
	logoFile="pack.png"

[[dependencies.lightmans_currency_bounties]]
    modId="bountiful"
    mandatory= true
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.lightmans_currency_bounties]]
    modId="extrabounties"
    mandatory= false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"