modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL=""
license="MIT"
[[mods]]
    modId="numismaticbounties"
    version="1.0"
    displayName="NumismaticBounties"
    description="Bountiful addon that change many trades to use Create:Numismatic coins"
	authors="DevDyna"
	logoFile="pack.png"