modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/DevDyna/DataThings/issues"
license="MIT"
[[mods]]
    modId="create_numismatic_bounties"
    version="2.0"
    displayName="Create : Numismatic Bounties"
    description="Bountiful addon that change many trades to use Create:Numismatic coins"
	authors="DevDyna"
	logoFile="pack.png"

[[dependencies.create_numismatic_bounties]]
    modId="bountiful"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_numismatic_bounties]]
    modId="extrabounties"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"