modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/DevDyna/DataThings/issues/new?template=chipped-express-bug.yaml"
license="MIT"
[[mods]]
    modId="chipped_express"
    version="1.2.4"
    displayName="ChippedExpress"
    description="Chipped mod still a good but cannot be automated , this mod allow autocrafting using other mods like AE2 or Create"

[[dependencies.chipped_express]]
	modId = "chipped"
	mandatory = true
	versionRange = "[1.0.0,)"
	ordering = "NONE"
	side = "BOTH"