import * as io from "../../../methods/io.mjs";
import * as core from "../core.mjs";

export const modid = "goety";
export const modid_focus = modid + "_focus";
export const modid_artifacts = modid + "_artifacts";
export const modid_rew_focus = modid_focus + "_rew";
export const modid_rew_artifacts = modid_artifacts + "_rew";
export const modid_any = modid + "_any";

export const langkeys = [modid_focus, modid_artifacts];
export const displayname = ["Necrotic Focuses", "Necrotic Souvenirs"];
//------------------------------------------//
export async function decree() {
  // DECREE
  io.mkFile(core.bounty_decrees_url + modid_focus + core.the_end, {
    requires: [modid],
    objectives: [core.treasures_id, core.resources_id,core.sculk_id, modid_any],
    rewards: [core.decree_id, core.rarities_id, modid_rew_focus, modid_any],
  });
  core.decor_out(modid_focus);

  io.mkFile(core.bounty_decrees_url + modid_artifacts + core.the_end, {
    requires: [modid],
    objectives: [core.treasures_id, core.resources_id,core.sculk_id, modid_any],
    rewards: [core.decree_id, core.rarities_id, modid_rew_artifacts, modid_any],
  });
  core.decor_out(modid_artifacts);
}
//------------------------------------------//
export async function pools() {
  // REWARD POOL
  io.mkFile(core.bounty_pools_url + modid_rew_focus + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 1 }, 1000, [
      "goety:rotting_focus",
      "goety:corruption_focus",
      "goety:ghastly_focus",
      "goety:sonic_boom_focus",
      "goety:leeching_focus",
      "goety:ice_storm_focus",
      "goety:ice_spike_focus",
      "goety:frost_breath_focus",
      "goety:scatter_focus",
      "goety:eruption_focus",
      "goety:sensing_focus",
      "goety:burrowing_focus",
      "goety:rotation_focus",
      "goety:barricade_focus",
      "goety:pulverize_focus",
      "goety:guardian_focus",
      "goety:bubble_stream_focus",
      "goety:flying_focus",
      "goety:whirlwind_focus",
      "goety:iron_hide_focus",
      "goety:hail_focus",
      "goety:bulwark_focus",
      "goety:iceology_focus",
      "goety:soul_heal_focus",
      "goety:end_walk_focus",
      "goety:teeth_focus",
      "goety:blink_focus",
      "goety:killing_focus",
      "goety:quaking_focus",
      "goety:cyclone_focus",
      "goety:steaming_focus",
      "goety:ghost_fire_focus",
      "goety:spooky_focus",
      "goety:whispering_focus",
      "goety:crafting_focus",
      "goety:vanguard_focus",
      "goety:chilling_focus",
      "goety:blizzard_focus",
      "goety:glow_light_focus",
      "goety:vexing_focus",
      "goety:wither_skull_focus",
      "goety:flame_strike_focus",
      "goety:skull_focus",
      "goety:illusion_focus",
      "goety:rupture_focus",
      "goety:reaping_focus",
      "goety:osseous_focus",
      "goety:updraft_focus",
      "goety:call_focus",
      "goety:blazing_focus",
      "goety:arrow_rain_focus",
      "goety:troop_focus",
      "goety:shockwave_focus",
      "goety:ender_chest_focus",
      "goety:fire_blast_focus",
      "goety:swarm_focus",
      "goety:shredding_focus",
      "goety:banish_focus",
      "goety:ignite_focus",
      "goety:tunnel_focus",
      "goety:bolting_focus",
      "goety:launch_focus",
      "goety:prisma_beam_focus",
      "goety:electrocute_focus",
      "goety:thunderbolt_focus",
      "goety:shocking_focus",
      "goety:weakening_focus",
      "goety:recall_focus",
      "goety:biting_focus",
      "goety:magma_bomb_focus",
      "goety:frostborn_focus",
      "goety:frost_nova_focus",
      "goety:feast_focus",
      "goety:poison_dart_focus",
      "goety:meteor_shower_focus",
      "goety:entangling_focus",
      "goety:overgrowth_focus",
      "goety:mauling_focus",
      "goety:charge_focus",
      "goety:command_focus",
      "goety:telekinesis_focus",
      "goety:monsoon_focus",
      "goety:blackguard_focus",
      "goety:bombardment_focus",
      "goety:lavaball_focus",
      "goety:magic_bolt_focus",
      "goety:fireball_focus",
      "goety:fire_breath_focus",
      "goety:blossoming_focus",
      "goety:grapple_focus",
      "goety:lightning_focus",
      "goety:hunting_focus",
      "goety:slimy_focus",
      "goety:trembling_focus",
      "goety:wind_blast_focus",
      "goety:cushion_focus",
      "goety:discharge_focus",
      "goety:soul_light_focus",
      "goety:bouncy_bubble_focus",
      "goety:sword_focus",
      "goety:tidal_focus",
      "goety:soul_bolt_focus",
      "goety:leaping_focus",
      "goety:phantasm_focus",
      "goety:biomine_focus",
      "goety:trident_storm_focus",
    ]),
  });
  core.decor_out(modid_rew_focus);

  io.mkFile(core.bounty_pools_url + modid_rew_artifacts + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 1 }, 1000, [
      "goety:undeath_potion",
      "goety:forbidden_grass",
      "goety:forbidden_piece",
      "goety:forbidden_fragment",
      "goety:necro_brazier",
      "goety:haunted_glass",
      "goety:haunted_glass_tinted",
      "goety:haunted_glass_mob",
      "goety:freezing_lamp",
      "goety:haunted_glass_mob_tinted",
      "goety:apparition_door",
      "goety:withered_manuscript",
      "goety:ominous_staff",
      "goety:dark_scythe",
      "goety:great_hammer",
      "goety:rampaging_axe",
      "goety:infernal_tome",
      "goety:thrash_glove",
      "goety:grave_glove",
      "goety:star_amulet",
      "goety:spiteful_belt",
      "goety:wayfarers_belt",
      "goety:alarming_charm",
      "goety:feline_amulet",
      "goety:sea_amulet",
      "goety:unholy_robe",
      "goety:nether_robe_warped",
      "goety:nether_robe",
      "goety:warlock_sash",
      "goety:wild_robe",
      "goety:warlock_robe_dark",
      "goety:warlock_robe",
      "goety:crone_hat",
      "goety:unholy_hat",
      "goety:dark_robe",
      "goety:grand_robe",
      "goety:necro_cape",
      "goety:nameless_cape",
      "goety:illusion_robe",
      "goety:illusion_robe_mirror",
      "goety:frost_robe_cryo",
      "goety:frost_robe",
      "goety:wind_robe",
      "goety:storm_robe",
      "goety:abyss_robe",
      "goety:witch_robe",
      "goety:witch_robe_hedge",
      "goety:witch_hat_hedge",
      "goety:witch_hat",
      "goety:amethyst_necklace",
      "goety:nameless_crown",
      "goety:necro_crown",
      "goety:nether_crown",
      "goety:abyss_crown",
      "goety:wild_crown",
      "goety:frost_crown",
      "goety:grand_turban",
      "goety:dark_hat",
      "goety:targeting_monocle",
      "goety:blazing_horn",
      "goety:pendant_of_hunger",
      "goety:dark_scroll",
      "goety:spent_totem",
      "goety:mystic_core",
      "goety:wind_core",
      "goety:hunger_core",
      "goety:animation_core",
      "goety:ominous_orb",
      "goety:heart_of_the_night",
      "goety:brew_bag",
      "goety:focus_bag",
      "goety:focus_pack",
      "goety:treasure_pouch",
      "goety:ring_of_want",
      "goety:ring_of_force",
      "goety:ring_of_the_forge",
      "goety:ring_of_the_dragon",
    ]),
  });
  core.decor_out(modid_rew_artifacts);

  // OBJECTIVE AND REWARD POOL
  io.mkFile(core.bounty_pools_url + modid_any + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 16 }, 1000, [
      "goety:soul_emerald",
      "goety:dark_ingot",
      "goety:shadow_essence",
      "goety:poison_quill_seed",
      "goety:chill_fabric",
      "goety:cursed_ingot",
      "goety:taglock_kit",
      "goety:ectoplasm",
      "goety:ominous_shard",
      "goety:quick_growing_seed",
      "goety:magic_fabric",
      "goety:ice_cube",
      "goety:soul_ruby",
      "goety:dark_fabric",
      "goety:spider_egg",
      "goety:occult_fabric",
      "goety:dark_metal_block",
      "goety:venomous_fang",
      "goety:cursed_metal_block",
      "goety:waystone",
      "goety:philosophers_stone",
      "goety:unholy_fabric",
      "goety:spirit_fabric",
      "goety:raging_matter",
      "goety:empty_focus",
      "goety:jade",
      "goety:savage_tooth",
      "goety:gale_fabric",
      "goety:warped_wartful_egg",
      "goety:magic_emerald",
    ]),
  });
  core.decor_out(modid_any);
}
//------------------------------------------//
