import * as io from "../../methods/io.mjs";
import * as core from "../core.mjs";

export const modid = "iceandfire";
export const modid_obj = modid + "_obj";
export const modid_rew = modid + "_rew";
export const modid_any = modid + "_any";

export async function decree() {
  io.mkFile(core.bounty_decrees_url + modid + core.the_end, {
    requires: [modid],
    objectives: [
      core.treasures_id,
      core.resources_id,
      modid_obj,
      modid_any,
      core.pottery_id,
      core.trims_id,
      core.explorer_id,
    ],
    rewards: [
      core.decree_id,
      core.rarities_id,
      modid_rew,
      modid_any,
      core.pottery_id,
      core.trims_id,
      core.explorer_id,
      core.enchants_id,
    ],
  });
  core.decor_out(modid);
}

export async function pools() {
  io.mkFile(core.bounty_pools_url + modid_obj + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 1 }, 1000, [
      "iceandfire:frost_stew",
      "iceandfire:sickly_dragon_meal",
      "iceandfire:nest",
      "iceandfire:frost_lily",
      "iceandfire:lightning_lily",
      "iceandfire:fire_stew",
      "iceandfire:dragon_meal",
      "iceandfire:fire_lily",
      "iceandfire:lightning_stew",
    ]),
  });
  core.decor_out(modid_obj);

  io.mkFile(core.bounty_pools_url + modid_rew + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 1 }, 1000, [
      "iceandfire:dragonforge_lightning_input",
      "iceandfire:dragonegg_amythest",
      "iceandfire:cyclops_eye",
      "iceandfire:dragonforge_ice_brick",
      "iceandfire:dragonforge_fire_brick",
      "iceandfire:dragonforge_ice_core_disabled",
      "iceandfire:banner_pattern_lightning_head",
      "iceandfire:dragonforge_fire_input",
      "iceandfire:banner_pattern_fire",
      "iceandfire:dragonegg_copper",
      "iceandfire:dragonegg_white",
      "iceandfire:dragonforge_ice_input",
      "iceandfire:dragonsteel_fire_ingot",
      "iceandfire:dragonegg_blue",
      "iceandfire:dragonsteel_lightning_ingot",
      "iceandfire:dread_key",
      "iceandfire:dragonegg_bronze",
      "iceandfire:dragonegg_silver",
      "iceandfire:dragonegg_black",
      "iceandfire:banner_pattern_ice",
      "iceandfire:dragonegg_sapphire",
      "iceandfire:dragonegg_red",
      "iceandfire:dragonforge_lightning_core_disabled",
      "iceandfire:dragonegg_gray",
      "iceandfire:dragonforge_lightning_brick",
      "iceandfire:dragonforge_fire_core_disabled",
      "iceandfire:dragonsteel_ice_ingot",
      "iceandfire:gorgon_head",
      "iceandfire:banner_pattern_lightning",
      "iceandfire:banner_pattern_fire_head",
      "iceandfire:dragonegg_electric",
      "iceandfire:ghost_ingot",
      "iceandfire:dragonegg_green",
      "iceandfire:banner_pattern_ice_head",
    ]),
  });
  core.decor_out(modid_rew);

  io.mkFile(core.bounty_pools_url + modid_any + core.the_end, {
    requires: [modid],
    content: core.contentCreator({ min: 1, max: 1 }, 1000, [
      "iceandfire:troll_tusk",
      "iceandfire:fire_dragon_heart",
      "iceandfire:lightning_dragon_blood",
      "iceandfire:dragonscales_red",
      "iceandfire:sea_serpent_scale_block_red",
      "iceandfire:summoning_crystal_fire",
      "iceandfire:dread_shard",
      "iceandfire:dragon_stick",
      "iceandfire:sea_serpent_scale_block_teal",
      "iceandfire:amphithere_feather",
      "iceandfire:silver_ingot",
      "iceandfire:dragon_skull_fire",
      "iceandfire:sea_serpent_scales_red",
      "iceandfire:dragon_skull_ice",
      "iceandfire:witherbone",
      "iceandfire:dragonscale_electric",
      "iceandfire:myrmex_jungle_egg",
      "iceandfire:dragonscales_copper",
      "iceandfire:sea_serpent_fang",
      "iceandfire:myrmex_jungle_resin",
      "iceandfire:manuscript",
      "iceandfire:dragonscale_black",
      "iceandfire:seaserpent_skull",
      "iceandfire:sea_serpent_scale_block_bronze",
      "iceandfire:hippogryph_skull",
      "iceandfire:dragonscales_bronze",
      "iceandfire:hippocampus_fin",
      "iceandfire:dragonscale_sapphire",
      "iceandfire:cyclops_skull",
      "iceandfire:fire_dragon_blood",
      "iceandfire:dragonscale_white",
      "iceandfire:deathworm_egg",
      "iceandfire:dragonscale_gray",
      "iceandfire:dragonscale_amythest",
      "iceandfire:sea_serpent_scales_teal",
      "iceandfire:dragonscales_sapphire",
      "iceandfire:lightning_dragon_heart",
      "iceandfire:shiny_scales",
      "iceandfire:dragonscales_silver",
      "iceandfire:dragonscale_copper",
      "iceandfire:cockatrice_skull",
      "iceandfire:sapphire_gem",
      "iceandfire:dragonscales_electric",
      "iceandfire:stymphalian_skull",
      "iceandfire:sea_serpent_scales_purple",
      "iceandfire:cockatrice_eye",
      "iceandfire:myrmex_jungle_chitin",
      "iceandfire:ice_dragon_blood",
      "iceandfire:deathworm_chitin_white",
      "iceandfire:dragonbone",
      "iceandfire:rotten_egg",
      "iceandfire:dragonscales_gray",
      "iceandfire:siren_tear",
      "iceandfire:dragonscales_green",
      "iceandfire:myrmex_desert_egg",
      "iceandfire:hydra_heart",
      "iceandfire:ectoplasm",
      "iceandfire:dragonscale_bronze",
      "iceandfire:sea_serpent_scales_blue",
      "iceandfire:deathworm_chitin_yellow",
      "iceandfire:dragonscales_white",
      "iceandfire:dragonscale_green",
      "iceandfire:dragonscales_blue",
      "iceandfire:dragonscales_black",
      "iceandfire:troll_skull",
      "iceandfire:dragonscales_amythest",
      "iceandfire:ambrosia",
      "iceandfire:dragon_skull_lightning",
      "iceandfire:summoning_crystal_lightning",
      "iceandfire:deathworm_egg_giant",
      "iceandfire:hippogryph_egg",
      "iceandfire:dragonscale_blue",
      "iceandfire:dragon_bone_block",
      "iceandfire:sea_serpent_scales_deepblue",
      "iceandfire:hydra_fang",
      "iceandfire:deathworm_chitin_red",
      "iceandfire:summoning_crystal_ice",
      "iceandfire:deathworm_tounge",
      "iceandfire:amphithere_skull",
      "iceandfire:sea_serpent_scale_block_green",
      "iceandfire:myrmex_desert_chitin",
      "iceandfire:pixie_dust",
      "iceandfire:dragonscale_silver",
      "iceandfire:pixie_wings",
      "iceandfire:ice_dragon_heart",
      "iceandfire:sea_serpent_scales_bronze",
      "iceandfire:dragonscale_red",
      "iceandfire:stymphalian_bird_feather",
      "iceandfire:hippogryph_talon",
      "iceandfire:sea_serpent_scale_block_deepblue",
      "iceandfire:myrmex_desert_resin",
      "iceandfire:hydra_skull",
      "iceandfire:sea_serpent_scales_green",
      "iceandfire:sea_serpent_scale_block_purple",
      "iceandfire:sea_serpent_scale_block_blue",
    ]),
  });
  core.decor_out(modid_any);
}

//require to be added to:
// - ../lang.mjs
// - ../../steps.mjs
